# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.TextField(max_length=20),
        ),
    ]
